#!/usr/bin/env sh
set -e

container_mode=${CONTAINER_MODE:-"http"}
running_migrations=${RUNNING_MIGRATIONS:-"false"}

echo "Mode du container: $container_mode"

initialStuff() {
    php artisan storage:link; \
    php artisan optimize:clear; \
    php artisan event:cache; \
    php artisan config:cache; \
    php artisan route:cache;

    if [ "${running_migrations}" = "true" ]; then
        echo "Migration de la base de donnée..."
        php artisan migrate --isolated --force;
    fi
}

if [ "$1" != "" ]; then
    exec "$@"
elif [ "${container_mode}" = "http" ]; then
    initialStuff
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.frankenphp.conf
elif [ "${container_mode}" = "scheduler" ]; then
    initialStuff
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.scheduler.conf
else
    echo "Pas de mode de container connu."
    exit 1
fi